### PR TITLE
Adding hdf5 support

### PR DESCRIPTION
**Pull request by MSteggles**
Hi,

Here's the modification for hdf5 support, little bit qnd but I think that's all it needs to be. Sets a flag for hdf5 if the wavefunctions are found in that format and reads them to the same variables as in the dat case. I've tested on .dat and .hdf5 with and without SOC, I'm pretty sure it's working. I personally also had to change the import of 'isround' in bandstructure.py to irrep.utility from irrep.__aux but I don't understand why.

Cheers,
Matthew

### CODE REVIEW

**Comment by stepan-tsirkin** [comment]
@MSteggles ,
thank you for your contribution. As ypu can see, the automaed testys have failed with message `Python version >= 3.8 required.`

I disabnled checks on the old python 3.7, and enabled for python 3.8 and 3.9. Please, update your branch from the master branch, and we'll see if the checks work.

Further, we will need a small test to make sure the HDF5 support will not be broken in future. For that a minimal (not obligatore physically meaningful) example is needed.

**Comment by MSteggles** [comment]
Oh dear, I'll fix this as soon as I have some free time. Thank you

**Comment by MSteggles** [comment]
Hi;

Apologies for the delay, I've been extremely busy with PhD work (handing in
~Christmas), thanks so much for your patience!
Hm yeah, just had a look - I'm a bit confused as h5py works from python
>=3.7, so I really don't know where the problem has come in. I'll have a
look and see if I can fix it. I'm also a little unsure of what you want:

1) Are you saying I just need to disable checks to see if the 3.8, 3.9
builds complete fine?
2) What would you like from a test? All it does is add the ability to read
that file format - would reading a given file and checking it's correct
against the .dat version suffice? The use of hdf5 comes from deep within
QEspresso

Looking forward to hearing from you

Best,
Matthew

**Comment by MSteggles** [comment]
Excellent stuff :-) Thanks for the help, I'll get on those and get in touch
if I have trouble.
Cheers,
Matthew

**Comment by stepan-tsirkin** [comment]
implemented in #85

**Comment by MSteggles** [comment]
Awesome! I (obviously) forgot about this a long time ago. Happy it's resolved and I hope it wasn't overly inconvenient.

M

**Pull request closed without merging**
