### PR TITLE
* new method for symsep -

### PR DESCRIPTION
**Pull request by stepan-tsirkin**
works much more precisely, including for norm-NOT-conserving pseudos

also allows transformations between different k-points, which allows to create the .dmn file for symmetry-adapted Wannier functions.  (coming soon in WannierBerri)

Other changes: 
* Now the characters are recalculated after separation, not copied (otherwise they were wrong)
* part of Kpoint.__init__ separated to a __init__traces() method, so that it can be reused in copy_sub()
* renamed v to verbosity, because it was causing collisions with some local variables
* fixed other issues with symsep
* updated test data for symsep, now separating by a rotational symmetry (-isymsep=3).
* -groupKramers default set to False (otehrwise, there was no way to switch it off

The idea of is simple. 

We assume that under a symmetry operations 

$$
g\circ\Psi_{n\mathbf{k}}(\mathbf{r}) = \Psi_{n\mathbf{k}}(g^{-1}\mathbf{r})  = \sum_m \Psi_{m,g\mathbf{k}}(\mathbf{r}) U^g_{mn}(\mathbf{k})   \quad\quad (1)
$$

, where $U^g_{mn}(\mathbf{k})$ is a unitary matrix. Previously, to evaluate it were computing the scalar product 

$$
\langle \Psi_{n\mathbf{k}(g^{-1}\mathbf{r})}  |  \Psi_{m,g\mathbf{k}(\mathbf{r})} \rangle  \quad\quad (2)
$$

However, such a scalar product requires the knowledge of the full-electron wave function (unless norm-conserving potentials are used) , therefore we had inaccuracies 

Instead, now we solve the equation (1) directly - find such matrix that transforms the wavefunctions (in this case we do not care if that are actually pseudo-wavefunctions, whjch are not orthonormal)

Thus, the essence is here 

https://github.com/irreducible-representations/irrep/blob/6aced8a193de8a2ce71f7879abda0360a78086b6/irrep/gvectors.py#L423-L433

and the right inverse of a rectangular matrix is 

https://github.com/irreducible-representations/irrep/blob/6aced8a193de8a2ce71f7879abda0360a78086b6/irrep/gvectors.py#L458-L459

### CODE REVIEW

**Comment by stepan-tsirkin** [comment]
@bmondal94 , I think it should not break compatibility with banduppy, but if it does, please let me know.

**Comment by bmondal94** [comment]
> @bmondal94 , I think it should not break compatibility with banduppy, but if it does, please let me know.

Works perfectly. No issues.

**Comment by stepan-tsirkin** [comment]
@MIraola , do you have any idea why the test is failing now ? according to the logs irreptables were succesfully installed, and on my computer it works fine.

**Comment by bmondal94** [comment]
@stepan-tsirkin 
I have a quick suggestion on the test failed: (if not resolved yet)

How about adding the python path explicitly in the test.yaml?

```
- name: Set PYTHONPATH
  run: echo "PYTHONPATH=$(pwd):$(pwd)/irreptables" >> $GITHUB_ENV

- name: Run tests
  run: pytest
  env:
    PYTHONPATH: ${{ env.PYTHONPATH }}
```

**Comment by stepan-tsirkin** [comment]
@bmondal94 , Thanks, it worked!

**Pull request merged**
